name: Code coverage test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    paths:
      - '**/analysis_options.yml'
      - '**/pubspec.yml'
      - '**/*.dart'
      - '!**/*.g.dart'
      - '!**/*.mocks.dart'
      - '!**/generated/**/*.dart'


jobs:
  lint_and_test:
    uses: SilentCatD/reusable_actions_and_workflows/.github/workflows/template_flutter_test.yml@main
    secrets:
      code_cov_token: ${{ secrets.CODECOV_TOKEN }}
